#!/bin/bash
# adaptation of super_netperf that works with -j/-k

run_netperf() {
	loops=$1
	shift
	for ((i=0; i<loops; i++)); do
		prefix="$(printf "%02d" $i) "
        (netperf -s 2 "$@" | sed -e "s/^/$prefix/") &
	done
	wait
}

if [ -z $1 ]; then
    echo "Usage: $0 <nstreams> <netperf args>"
    exit 1
fi

run_netperf "$@" | perl -ln -e 'BEGIN { $sum = 0; } END { print "AGGREGATE_THROUGHPUT=$sum"; } if (/ THROUGHPUT=(\S+)$/) { $sum += $1; } print;'
